name: Maven test
on:
  workflow_dispatch:
    inputs:
      ignore_cache:
        description: "Ignore the repository cache for this run"
        required: false
        default: "false"
  pull_request:

permissions:
  contents: read
jobs:
  dirty-waters:
    runs-on:
        ubuntu-latest
    permissions:
      pull-requests: write # To comment on a Pull Request
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Dirty Waters Analysis
        uses: chains-project/dirty-waters-action@2a3c15b5ec945452ea99337ecb9c67cad1d6302d
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: maven
          #config: ./config/dirty-waters.json
          #config: ./config/dirty-waters-critical.json
          ignore_cache: false
          debug: true
          gradual_report: true
          #fail_on_min_severity: "critical"
